### ISSUE TITLE
indel positions in alignment

### ISSUE THREAD

**Issue by zenalapp** [alexdonath/gappy#1]
Could you add an output file containing the genomic positions of the indels based on the input fasta file? It could be something as simple as a two-column text file with the start and end positions of each indel.

**Comment by alexdonath** [comment]
Hi,
It is currently not easy to extract this type of information. I am working on a reimplementation of the method that will include this feature.

alex

**Comment by alexdonath** [comment]
Hi,
How about a four-column text file that includes the alignment file name, the start and stop position, and the identifier of the sequences that share this deletion?

alex

**Comment by zenalapp** [comment]
That sounds perfect - thanks!

**Comment by alexdonath** [comment]
Hi,
I took the liberty to completely redesign gappy in python. This made it easier to include the changes you have asked for. And it gave me the opportunity to learn some python ;-)
I have just pushed the initial release of [gappy2 to github](https://github.com/alexdonath/gappy2). Do you mind testing it out?

Thanks,
alex

**Comment by zenalapp** [comment]
I just tried it out, and it worked - thanks!

**Comment by alexdonath** [comment]
Glad that it did.
